version: '3.9'
x-common: &common
  restart: unless-stopped
  tty: true
x-config: &config
  ENV_FILE: /etc/server.conf
  CFG_LOG_LEVEL: -1
  CFG_GRPC_HOST: grpc
services:
#  etcd0:
#    <<: *common
#    image: quay.io/coreos/etcd:v3.5.1
#    command:
#      - /usr/local/bin/etcd
#      - --name
#      - etcd0
#      - --initial-advertise-peer-urls
#      - http://172.255.254.101:2380
#      - --listen-peer-urls
#      - http://0.0.0.0:2380
#      - --advertise-client-urls
#      - http://172.255.254.101:2379
#      - --listen-client-urls
#      - http://0.0.0.0:2379
#      - --initial-cluster
#      - "etcd0=http://172.255.254.101:2380"
#      - --initial-cluster-state
#      - new
#      - --initial-cluster-token
#      - etcd-docker-cluster
#    ports:
#      - "14100:2379"
#      - "14101:2380"
#    networks:
#      backend:
#        aliases:
#          - etcd0
#        ipv4_address: 172.255.254.101
#    volumes:
#      - /usr/share/ca-certificates/:/etc/ssl/certs:ro
#      - ${TMP_PATH}/etcd0:/etcd-data
#  maria:
#    <<: *common
#    image: mariadb:10.6-focal
#    environment:
#      MYSQL_DATABASE: ${MARIA_DATABASE}
#      MYSQL_USER: ${MARIA_USERNAME}
#      MYSQL_PASSWORD: ${MARIA_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${MARIA_PASSWORD}
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
#    ports:
#      - "14200:3306"
#    networks:
#      backend:
#        aliases:
#          - maria
#        ipv4_address: 172.255.254.102
#    volumes:
#      - ${TMP_PATH}/mariadb:/var/lib/mysql:delegated
#  mongo:
#    <<: *common
#    image: mongo:5.0-focal
#    environment:
#      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#    ports:
#      - "14300:27017"
#    networks:
#      backend:
#        aliases:
#          - mongo
#        ipv4_address: 172.255.254.103
#    volumes:
#      - ${TMP_PATH}/mongodb:/data/db:delegated
#  rabbitmq:
#    <<: *common
#    image: rabbitmq:3.9-management
#    ports:
#      - "14500:5672"
#      - "14580:15672"
#    networks:
#      backend:
#        aliases:
#          - rabbitmq
#        ipv4_address: 172.255.254.105
#    volumes:
#      - ${TMP_PATH}/rabbitmq/conf:/etc/rabbitmq:delegated
#      - ${TMP_PATH}/rabbitmq/data:/var/lib/rabbitmq:delegated
#  redis:
#    <<: *common
#    image: redis:6.2-bullseye
#    command: "redis-server --appendonly yes --loglevel warning --requirepass ${REDIS_PASSWORD}"
#    ports:
#      - "14600:6379"
#    networks:
#      backend:
#        aliases:
#          - redis
#        ipv4_address: 172.255.254.106
#    volumes:
#      - ${TMP_PATH}/redis:/data:delegated
  grpc:
    <<: *common
    image: ${IMAGE_LCL}
    environment:
      <<: *config
    ports:
      - "15051:50051"
    networks:
      service_network:
        aliases:
          - grpc
        ipv4_address: 172.255.254.200
    volumes:
      - ${PWD}/.env:/etc/server.conf:ro
#  gateway:
#    <<: *common
#    image: ${IMAGE_LCL}
#    command:
#      - +
#      - -mode=gateway
#    environment:
#      <<: *config
#    ports:
#      - "15080:8080"
#    networks:
#      service_network:
#        aliases:
#          - gateway
#        ipv4_address: 172.255.254.201
#    volumes:
#      - ${PWD}/.env:/etc/server.conf:ro
networks:
  service_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.255.254.0/24
