version: '3.9'
x-common: &common
  restart: unless-stopped
  tty: true
services:
  etcd0:
    <<: *common
    image: quay.io/coreos/etcd:v3.5.1
    command: 
      - /usr/local/bin/etcd
      - --name
      - etcd0
      - --initial-advertise-peer-urls
      - http://172.255.255.100:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --advertise-client-urls
      - http://172.255.255.100:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --initial-cluster
      - "etcd0=http://172.255.255.100:2380,etcd1=http://172.255.255.101:2380,etcd2=http://172.255.255.102:2380"
      - --initial-cluster-state
      - new
      - --initial-cluster-token
      - etcd-docker-cluster
    ports:
      - 14100:2379
      - 14101:2380
    networks:
      etcd_network:
        aliases:
          - etcd0
        ipv4_address: 172.255.255.100
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
      - /tmp/docker-recipes/etcd0:/etcd-data
  etcd1:
    <<: *common
    image: quay.io/coreos/etcd:v3.5.1
    command: 
      - /usr/local/bin/etcd
      - --name
      - etcd1
      - --initial-advertise-peer-urls
      - http://172.255.255.101:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --advertise-client-urls
      - http://172.255.255.101:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --initial-cluster
      - "etcd0=http://172.255.255.100:2380,etcd1=http://172.255.255.101:2380,etcd2=http://172.255.255.102:2380"
      - --initial-cluster-state
      - new
      - --initial-cluster-token
      - etcd-docker-cluster
    ports:
      - 2379
      - 2380
    networks:
      etcd_network:
        aliases:
          - etcd1
        ipv4_address: 172.255.255.101
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
      - /tmp/docker-recipes/etcd1:/etcd-data
  etcd2:
    <<: *common
    image: quay.io/coreos/etcd:v3.5.1
    command: 
      - /usr/local/bin/etcd
      - --name
      - etcd2
      - --initial-advertise-peer-urls
      - http://172.255.255.102:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --advertise-client-urls
      - http://172.255.255.102:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --initial-cluster
      - "etcd0=http://172.255.255.100:2380,etcd1=http://172.255.255.101:2380,etcd2=http://172.255.255.102:2380"
      - --initial-cluster-state
      - new
      - --initial-cluster-token
      - etcd-docker-cluster
    ports:
      - 2379
      - 2380
    networks:
      etcd_network:
        aliases:
          - etcd2
        ipv4_address: 172.255.255.102
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
      - /tmp/docker-recipes/etcd2:/etcd-data
networks:
  etcd_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.255.255.0/24
