version: '3.9'
x-common: &common
  restart: unless-stopped
  tty: true
services:
  redis:
    <<: *common
    image: redis:6.2-bullseye
    command: "redis-server --appendonly yes --loglevel warning --requirepass ${REDIS_PASSWORD}"
    ports:
      - 14600:6379
    volumes:
      - /tmp/docker-recipes/redis:/data:delegated
