version: '3.9'
x-common: &common
  restart: unless-stopped
  tty: true
services:
  mongo:
    <<: *common
    image: mongo:5.0-focal
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 14300:27017
    volumes:
      - /tmp/docker-recipes/mongodb:/data/db:delegated
