version: '3.9'
x-common: &common
  restart: unless-stopped
  tty: true
services:
  maria:
    <<: *common
    image: mariadb:10.6-focal
    environment:
      MYSQL_DATABASE: ${MARIA_DATABASE}
      MYSQL_USER: ${MARIA_USERNAME}
      MYSQL_PASSWORD: ${MARIA_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIA_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - 14200:3306
    volumes:
      - /tmp/docker-recipes/mariadb:/var/lib/mysql:delegated
